# PipeWire PulseAudio Server Configuration
# We enable TCP listening so the host can connect or we can tunnel.

context.properties = {
    ## Properties for the PulseAudio server
    #server.address = [ "unix:native", "tcp:4713" ]
}

context.modules = [
    { name = libpipewire-module-protocol-pulse
        args = {
            # the address to listen on
            server.address = [ "unix:native", "tcp:4713" ]
            #check.access.socket = true
        }
    }
]

stream.properties = {
    #node.latency = 1024/48000
    #node.autoconnect = true
}
