[General]
# Name of the system
Name=btbox

# Default adapter class — Audio/Video device
Class=0x200414

# Discoverable timeout 0 = always discoverable
DiscoverableTimeout=0

# Pairable timeout 0 = always pairable
PairableTimeout=0

# Enable all audio profiles
Enable=Source,Sink,Media,Socket

# Fast connectable for quicker reconnection
FastConnectable=true

[Policy]
# AutoEnable defines if the controller should be powered on by default.
AutoEnable=true

# Reconnect on boot to previously paired devices
ReconnectAttempts=7
ReconnectIntervals=1,2,4,8,16,32,64
