[General]
# Name of the system
Name=btbox

# Default adapter class
Class=0x000100

# Discoverable timeout 0 = always discoverable
DiscoverableTimeout=0

# Pairable timeout 0 = always pairable
PairableTimeout=0

[Policy]
# AutoEnable defines if the controller should be powered on by default.
AutoEnable=true
